version: "3.9"

services:
  web:
    container_name: "skilltrees-web"
    ports:
      - "3000:3000"
    tty: true
    build:
      context: ./web
      dockerfile: Dockerfile
    networks:
      - frontend
      - backend

  api:
    container_name: "skilltrees-api"
    ports:
      - "8080:8080"
    tty: true
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - backend

  db:
    container_name: "skilltrees-db"
    image: postgres:14
    env_file: .env
    ports:
      - "5423:5432"
    tty: true
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend

networks:
  frontend: {}
  backend: {}
