services:
  web:
    # command: dev --prefix ./web
    command: dev
    volumes:
      - ./web:/usr/src/web
      - /usr/src/web/node_modules
      - /usr/src/web/.next
  api:
    # command: dev --prefix ./api
    command: dev
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
  db:
    volumes:
      - .:/usr/data
