services:
  web:
    command: dev --prefix ./web
    volumes:
      - .:/usr/src/web
      - /usr/src/web/node_modules
      - /usr/src/web/.next
  api:
    command: dev --prefix ./api
    volumes:
      - .:/usr/src/api
      - /usr/src/api/node_modules
  db:
    volumes:
      - .:/usr/data
