version: "3.9"

services:
  web:
    container_name: "skilltrees-web"
    env_file: .env
    ports:
      - "3000:3000"
    restart: always
    tty: true
    build:
      context: ./web
      dockerfile: Dockerfile
    networks:
      - default

  api:
    container_name: "skilltrees-api"
    ports:
      - "8080:8080"
    restart: always
    tty: true
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - default

  db:
    container_name: "skilltrees-db"
    image: postgres:14
    env_file: .env
    ports:
      - "5432:5432"
    tty: true
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - default

networks:
  default:
    ipam:
      driver: default
